name_maximum: 100
string_maximum: 255
years: 100
host: "localhost:3000"
remember: "1"
book_in_page: 6
average_rate: 2
limit_review: 5
activites: 10
user_in_page: 6
exp_token: <%= Time.now.to_i + 4 * 3600 %>
secret_encode: HS256
